### ISSUE TITLE
Connection problems with P2 after package update

### ISSUE THREAD

**Issue by jbussmann** [naneos-org/python-naneos-devices#15]
I updated the package to the newest version (v1.0.25) and while running Python 3.11 on Windows 10, the example code from the PiPY page gives the following output:

```
Found Partector2 devices:
Serial number: 8765, Port: COM84
 2024-03-05 14:27:21,042 - naneos.partector.blueprints._partector_blueprint - WARNING - Could not connect to SNCOM84 on None (_partector_blueprint.py:421) 
 2024-03-05 14:27:21,044 - naneos.partector.partector2 - INFO - SNCOM84 has FW0. -> Using legacy data structure. (partector2.py:25) 
Empty DataFrame
Columns: [runtime_min, idiff_global, ucor_global, hiresADC1, hiresADC2, EM_amplitude1, EM_amplitude2, T, RHcorr, device_status, deposition_voltage, batt_voltage, flow_from_dp, LDSA, diameter, number, dP, P_average]       
Index: []
```

Using an older version of the package works as expected. v0.7.3 is the first to break and yields the following output: 

```
2024-03-05 14:39:57,021 - naneos.partector.blueprints._partector_blueprint - INFO - Connected to SNNone on COM84 (_partector_blueprint.py:311)
Found Partector2 devices:
Serial number: 8765, Port: COM84
2024-03-05 14:39:57,299 - naneos.partector.blueprints._partector_blueprint - INFO - Connected to SNNone on COM84 (_partector_blueprint.py:311)
2024-03-05 14:39:57,553 - naneos.partector.blueprints._partector_blueprint - WARNING - Could not get device info! (_partector_blueprint.py:345)
Empty DataFrame
Columns: [runtime_min, idiff_global, ucor_global, hiresADC1, hiresADC2, EM_amplitude1, EM_amplitude2, T, RHcorr, device_status, deposition_voltage, batt_voltage, flow_from_dp, LDSA, diameter, number, 
dP, P_average]
Index: []
Exception in thread naneos-partector-thread:
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "c:\Code\Python\.venvold\Lib\site-packages\naneos\partector\blueprints\_partector_blueprint.py", line 41, in run
    if self._ser.isOpen():
       ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isOpen'
```

**Comment by pkuery** [comment]
Same issue here, python 3.11.8, win 10

**Comment by huegi** [comment]
Holy moly thx boys, I will go over this Problem with my Windows Computer.

Last updates where pushed in a rush, because of Feature requests...

**Comment by huegi** [comment]
@pkuery and @jbussmann Could you please install: pip install -i https://test.pypi.org/simple/ naneos-devices and check if the problem still exists?

**Comment by huegi** [comment]
Es gibt jetzt Version 1.0.27 mit einer kleinen Änderung die bei Vales computer aufgetretten ist. Auch auf test.pypi

Patricks computer hat irgendwie gar nicht funktioniert aber da bin ich mir noch nicht ganz sicher ob ich schuld bin ;) Bei @ValentinBhend läufts auf jeden fall.

**Comment by jbussmann** [comment]
I installed the package using `pip install -i https://test.pypi.org/simple/ naneos-devices` after first uninstalling the PyPI package. This resulted in v1.0.30 being installed which doesn't work at all. No output of any kind. So downgrading to v1.0.27 using `pip install -i https://test.pypi.org/simple/ naneos-devices==1.0.27` yielded something similar as before:

```
Found Partector2 devices:
Serial number: 8765, Port: COM84
 2024-03-12 09:42:49,060 - naneos.partector.blueprints._partector_blueprint - WARNING - SNCOM84 not found! Checker is running in the background. (_partector_blueprint.py:407) 
 2024-03-12 09:42:49,561 - naneos.partector.blueprints._partector_blueprint - ERROR - SNCOM84 on port None could not be opened! Tries: 77948 (_partector_blueprint.py:434) 
 2024-03-12 09:42:49,561 - naneos.partector.blueprints._partector_blueprint - WARNING - SNCOM84 on port None needed 77948 tries to connect. (_partector_blueprint.py:436) 
 2024-03-12 09:42:49,562 - naneos.partector.blueprints._partector_blueprint - WARNING - Could not connect to SNCOM84 on None (_partector_blueprint.py:444) 
 2024-03-12 09:42:49,563 - naneos.partector.partector2 - INFO - SNCOM84 has FW0. -> Using legacy data structure. (partector2.py:25) 
Empty DataFrame
Columns: [runtime_min, idiff_global, ucor_global, hiresADC1, hiresADC2, EM_amplitude1, EM_amplitude2, T, RHcorr, device_status, deposition_voltage, batt_voltage, flow_from_dp, LDSA, diameter, number, dP, 
P_average]
Index: []
```

I already last time noted that the messages say `SNCOM84` which seems odd. I disregarded this, however this time @pkuery insisted on investigating this further. It became clear rather quick that the Partector2 class expects a constructor call of `Partector2(serial_number, port, verb_freq)`, unlike how the example code calls the constructor. Modifying the example code to specifically pass the port yields following result:

```
Found Partector2 devices:
Serial number: 8765, Port: COM84
 2024-03-12 09:44:41,810 - naneos.partector.blueprints._partector_blueprint - INFO - Connected to SNNone on COM84 (_partector_blueprint.py:441) 
 2024-03-12 09:44:41,861 - naneos.partector.partector2 - INFO - SN8765 has FW315. -> Using V299 data structure. (partector2.py:22) 
Empty DataFrame
Columns: [runtime_min, idiff_global, ucor_global, hiresADC1, hiresADC2, EM_amplitude1, EM_amplitude2, T, RHcorr, device_status, deposition_voltage, batt_voltage, flow_from_dp, LDSA, diameter, number, dP, 
P_average, em_gain1, em_gain2]
Index: []
```

So this seems to at least partially work but the DataFrame is still empty.
